/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classifyimages;

import java.awt.event.KeyEvent;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Mahmoud
 */
public class MainFrame extends javax.swing.JFrame {
    // the index of the images
    static int pos = 0;
   Next_prev np = new Next_prev();
   Move_1 m1 = new Move_1();
   Move_2 m2 = new Move_2();
   Move_3 m3 = new Move_3();
   Move_4 m4 = new Move_4();
   Move_5 m5 = new Move_5();
   

   
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //showImage(pos);
        Menu mu = new Menu();
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel_image = new javax.swing.JLabel();
        jButton_next = new javax.swing.JButton();
        jButton_prev = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_next.setText("Next");
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });
        jButton_next.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_nextKeyPressed(evt);
            }
        });

        jButton_prev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_prev.setText("Prev");
        jButton_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_prevActionPerformed(evt);
            }
        });
        jButton_prev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_prevKeyPressed(evt);
            }
        });

        jButton_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_1.setText("1");
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });

        jButton_2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_2.setText("2");
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });

        jButton_3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_3.setText("3");
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });

        jButton_4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_4.setText("4");
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });

        jButton_5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_5.setText("5");
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setText("help");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_next, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_next, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_prevActionPerformed
       //Bacterial spot
      if(Menu.btn == 1)
      {
          try {
              np.bacterial_spot_prev();
          } catch (IOException ex) {
              Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
          }

      }

        //Early blight
      else if(Menu.btn == 2)
      {
         np.early_blight_prev();
        //Late Blight
      } else if(Menu.btn == 3)
      {
         np.late_blight_prev();

      } else if(Menu.btn == 4){
         np.leaf_Mold_prev();
        
      }else if(Menu.btn == 5){
         np.septoria_leaf_spot_prev();
      }else if(Menu.btn == 6){
         np.spider_mite_prev();
      }else if(Menu.btn == 7){
         np.target_spot_prev();
      }else if(Menu.btn == 8){
         np.mosaic_virus_prev();
      }else if(Menu.btn == 9){
         np.yellow_curv_virus_prev();
      }else ;
 
    }//GEN-LAST:event_jButton_prevActionPerformed

    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
      //Bacterial spot
      if(Menu.btn == 1)
      {
          try {
              np.bacterial_spot_next();
          } catch (IOException ex) {
              Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
 
        //Early blight
      else if(Menu.btn == 2)
      {
         np.early_blight_next();

        //Late Blight
      } else if(Menu.btn == 3)
      {
         np.late_blight_next();
      } else if(Menu.btn == 4){
         np.leaf_Mold_next();
      }else if(Menu.btn == 5){
         np.septoria_leaf_spot_next();
      }else if(Menu.btn == 6){
         np.spider_mite_next();
      }else if(Menu.btn == 7){
         np.target_spot_next();

      }else if(Menu.btn == 8){
         np.mosaic_virus_next();
      }else if(Menu.btn == 9){
         np.yellow_curv_virus_next();
      }else ;
   
    }//GEN-LAST:event_jButton_nextActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        if(Menu.btn == 1){
            m1.moveBacterial_spot();
            }else if (Menu.btn == 2){
            m1.moveEarly_blight();
        }else if (Menu.btn == 3){
            m1.moveLate_blight();
        }else if (Menu.btn == 4){
            m1.moveLeaf_mold();

        }else if (Menu.btn == 5){
            m1.moveSeptoria_leaf_spot();
        }else if (Menu.btn == 6){
            m1.moveSpider_mites();
        }else if (Menu.btn == 7){
            m1.moveTarget_Spot();
        }else if (Menu.btn == 8){
            m1.moveMosaic_virus();
        }else if (Menu.btn == 9){
            m1.moveYellow_Leaf_Curl_Virus();
        }else ;  
 
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
        if(Menu.btn == 1){
            m2.moveBacterial_spot();
        } else if (Menu.btn == 2){
            m2.moveEarly_blight();
        }else if (Menu.btn == 3){
            m2.moveLate_blight();

        }else if (Menu.btn == 4){
            m2.moveLeaf_mold();
        }else if (Menu.btn == 5){
            m2.moveSeptoria_leaf_spot();
        }else if (Menu.btn == 6){
            m2.moveSpider_mites();
        }else if (Menu.btn == 7){
            m2.moveTarget_Spot();
        }else if (Menu.btn == 8){
            m2.moveMosaic_virus();
        }else if (Menu.btn == 9){
            m2.moveYellow_Leaf_Curl_Virus();
        }else ;
        
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
         if(Menu.btn == 1){
            m3.moveBacterial_spot();
        }  else if (Menu.btn == 2){
            m3.moveEarly_blight();
        }else if (Menu.btn == 3){
            m3.moveLate_blight();
        }else if (Menu.btn == 4){
            m3.moveLeaf_mold();
        }else if (Menu.btn == 5){
            m3.moveSeptoria_leaf_spot();
        }else if (Menu.btn == 6){
            m3.moveSpider_mites();
        }else if (Menu.btn == 7){
            m3.moveTarget_Spot();
        }else if (Menu.btn == 8){
            m3.moveMosaic_virus();
        }else if (Menu.btn == 9){
            m3.moveYellow_Leaf_Curl_Virus();
        }else ;
       
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        if(Menu.btn == 1){
            m4.moveBacterial_spot();
        }else if (Menu.btn == 2){
            m4.moveEarly_blight();
        }else if (Menu.btn == 3){
            m4.moveLate_blight();
        }else if (Menu.btn == 4){
            m4.moveLeaf_mold();
        }else if (Menu.btn == 5){
            m4.moveSeptoria_leaf_spot();
        }else if (Menu.btn == 6){
            m4.moveSpider_mites();
        }else if (Menu.btn == 7){
            m4.moveTarget_Spot();
        }else if (Menu.btn == 8){
            m4.moveMosaic_virus();
        }else if (Menu.btn == 9){
            m4.moveYellow_Leaf_Curl_Virus();
        }else ;
        
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
        if(Menu.btn == 1){
            m5.moveBacterial_spot();
        }else if (Menu.btn == 2){
            m5.moveEarly_blight();
        }else if (Menu.btn == 3){
            m5.moveLate_blight();

        }else if (Menu.btn == 4){
            m5.moveLeaf_mold();
        }else if (Menu.btn == 5){
            m5.moveSeptoria_leaf_spot();
        }else if (Menu.btn == 6){
            m5.moveSpider_mites();
        }else if (Menu.btn == 7){
            m5.moveTarget_Spot();
        }else if (Menu.btn == 8){
            m5.moveMosaic_virus();
        }else if (Menu.btn == 9){
            m5.moveYellow_Leaf_Curl_Virus();
        }else ;
    
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_nextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_nextKeyPressed

       if(evt.getKeyCode() == KeyEvent.VK_RIGHT)
       {
           if(Menu.btn ==1)
               try {
                   np.bacterial_spot_next();
           } catch (IOException ex) {
               Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
           }

           else if (Menu.btn == 2)
               np.early_blight_next();
           else if (Menu.btn == 3)
               np.late_blight_next();
           else if (Menu.btn == 4)
               np.leaf_Mold_next();
           else if (Menu.btn == 5)
               np.septoria_leaf_spot_next();
           else if (Menu.btn == 6)
               np.spider_mite_next();
           else if (Menu.btn == 7)
               np.target_spot_next();
           else if (Menu.btn == 8)
               np.mosaic_virus_next();
           else if (Menu.btn == 9)
               np.yellow_curv_virus_next();
           else ;
          
       }
            
    }//GEN-LAST:event_jButton_nextKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Menu m = new Menu();
      m.setVisible(true);
      m.setLocationRelativeTo(null);
      m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_prevKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_prevKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_LEFT)
       {
           if(Menu.btn ==1)
               try {
                   np.bacterial_spot_prev();
           } catch (IOException ex) {
               Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
           }

           else if (Menu.btn == 2)
               np.early_blight_prev();
           else if (Menu.btn == 3)
               np.late_blight_prev();
           else if (Menu.btn == 4)
               np.leaf_Mold_next();
           else if (Menu.btn == 5)
               np.septoria_leaf_spot_prev();
           else if (Menu.btn == 6)
               np.spider_mite_prev();
           else if (Menu.btn == 7)
               np.target_spot_prev();
           else if (Menu.btn == 8)
               np.mosaic_virus_prev();
           else if (Menu.btn == 9)
               np.yellow_curv_virus_prev();
           else ;
 
       }
    }//GEN-LAST:event_jButton_prevKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.dispose();
       Welcome w = new Welcome();
       w.setVisible(true);
       w.setDefaultCloseOperation(EXIT_ON_CLOSE);
       w.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_next;
    private javax.swing.JButton jButton_prev;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel_image;
    // End of variables declaration//GEN-END:variables
}
